---
- import_role:
    name: k8s
    tasks_from: bootstrap

- import_role:
    name: containerd
    tasks_from: install_containerd_as_k8s_runtime

- import_role:
    name: k8s
    tasks_from: install_k8s_packages
