---
- import_role:
    name: k8s
    tasks_from: add_k8s_keyring

- name: Install kubectl
  apt:
    name: '{{ packages }}'
    state: present
    install_recommends: false
    force: true
    update_cache: true
  vars:
    packages:
      - kubectl

# Hold the kubectl to prevent automatic updates
- name: Hold kubectl
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubectl
