---
- import_role:
    name: utils
    tasks_from: read_system_info

- name: Add gpp key to fetch containerd from docker
  block:
    - name: Add signing key
      apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add repository into sources list
      apt_repository:
        repo: "deb [arch={{ dep_architecture }}] https://download.docker.com/linux/\
               {{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

- name: Install containerd.io
  apt:
    name: '{{ packages }}'
    state: present
    install_recommends: false
    force: true
    update_cache: true
  vars:
    packages:
      - containerd.io

# Hold the installed packages to prevent automatic updates
- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - containerd.io

- name: update containerd config
  copy:
    src: "{{ role_path }}/files/config.toml"
    dest: "/etc/containerd/config.toml"
    owner: root
    group: root
    mode: 0644

- name: Restart containerd service
  service:
    name: containerd
    state: restarted
