---
# In Chain, Access Github very slow, so don't remove openclash
# - name: Reomve openclash
#   community.general.opkg:
#     name: luci-app-openclash
#     state: absent

# community.general.opkg currently does not support installing 
# packages from local and remote urls
- name: Get openclash package
  get_url: 
    url: "{{ openclash_url }}"
    dest: "{{ openclash_folder }}/luci-app-openclash.ipk"
    mode: 0644
    force: true
    timeout: 30

- name: Install openclash
  shell: "opkg install {{ openclash_folder }}/luci-app-openclash.ipk"
