---
- hosts: localhost
  connection: local
  become: true
  become_user: root
  tasks:
    - import_role:
        name: docker

    - import_role:
        name: k8s
        tasks_from: install_kubectl

    - import_role:
        name: k8s
        tasks_from: install_tanka

    - import_role:
        name: golang
        tasks_from: install_golang
