---
- hosts: k8s-master
  become: true
  become_user: root
  tasks:
    - import_role:
        name: k8s
        tasks_from: bootstrap

    - import_role:
        name: containerd
        tasks_from: install_containerd_as_k8s_runtime

    - import_role:
        name: k8s
        tasks_from: install_k8s_packages

    - import_role:
        name: k8s
        tasks_from: setup_master
    
    - import_role:
        name: k8s
        tasks_from: install_calico
    
    - import_role:
        name: k8s
        tasks_from: install_calicoctl
