---
- hosts: gl_axt1800
  become: true
  become_user: root
  tasks:
    - import_role:
        name: gl_router_web
        tasks_from: update_manager_web

    - import_role:
        name: golink
        tasks_from: install-glinet-golinks
    
    - import_role:
        name: openclash
        tasks_from: install_for_gl_axt1800
